In [31]:
# Dependencies
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import requests
import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()


url = "https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol=CL&apikey=OXORD93CJRCKNW7W"
format = "json"

# Get country information in JSON format
data = requests.get(f"{url}countries?format=json").json()

# First element is general information, second is countries themselves
#data

In [23]:
# Here is your API key: OXORD93CJRCKNW7W. Please record this API key for future access to Alpha Vantage.

In [3]:
data.keys()

dict_keys(['Meta Data', 'Monthly Time Series'])

In [4]:
data["Monthly Time Series"]

data.keys()

time_series = data["Monthly Time Series"]

dates = time_series.keys()

df = pd.DataFrame(time_series)
df = df.astype(float)

In [5]:
df.head()

,2019-05-07,2019-04-30,2019-03-29,2019-02-28,2019-01-31,2018-12-31,2018-11-30,2018-10-31,2018-09-28,2018-08-31,...,1998-11-30,1998-10-30,1998-09-30,1998-08-31,1998-07-31,1998-06-30,1998-05-29,1998-04-30,1998-03-31,1998-02-27
1. open,72.08,68.38,6.592000e+01,64.90,5.924000e+01,6.346000e+01,5.963000e+01,6.696000e+01,65.74,66.83,...,88.75,68.56,72.13,92.75,88.25,87.00,89.50,86.50,80.94,74.00
2. high,72.47,72.85,6.860690e+01,67.47,6.485000e+01,6.588000e+01,6.398500e+01,6.780000e+01,69.29,68.43,...,95.00,90.00,77.00,93.31,98.88,92.13,91.00,91.50,88.88,81.81
3. low,69.55,67.25,6.478000e+01,64.20,5.862000e+01,5.750500e+01,5.932000e+01,5.741000e+01,64.95,65.01,...,85.50,67.13,65.06,71.88,87.75,84.94,84.88,81.50,78.63,73.25
4. close,70.51,72.79,6.854000e+01,65.87,6.468000e+01,5.952000e+01,6.352000e+01,5.955000e+01,66.95,66.41,...,85.63,88.38,68.75,72.13,92.25,88.00,87.00,89.69,86.75,81.19
5. volume,14861310.00,67311179.00,7.109046e+07,72086027.00,1.044044e+08,1.000546e+08,1.095778e+08,1.188532e+08,57660645.00,64553153.00,...,17763100.00,28560200.00,32010900.00,20730000.00,15514900.00,13906800.00,12391200.00,17486000.00,16803000.00,16593000.00

In [6]:
df_price = df.drop(['1. open','4. close','5. volume'])

In [7]:
df_price.loc['mean'] = df_price.mean()

In [8]:
df_price.head()

,2019-05-07,2019-04-30,2019-03-29,2019-02-28,2019-01-31,2018-12-31,2018-11-30,2018-10-31,2018-09-28,2018-08-31,...,1998-11-30,1998-10-30,1998-09-30,1998-08-31,1998-07-31,1998-06-30,1998-05-29,1998-04-30,1998-03-31,1998-02-27
2. high,72.47,72.85,68.60690,67.470,64.850,65.8800,63.9850,67.800,69.29,68.43,...,95.00,90.000,77.00,93.310,98.880,92.130,91.00,91.5,88.880,81.81
3. low,69.55,67.25,64.78000,64.200,58.620,57.5050,59.3200,57.410,64.95,65.01,...,85.50,67.130,65.06,71.880,87.750,84.940,84.88,81.5,78.630,73.25
mean,71.01,70.05,66.69345,65.835,61.735,61.6925,61.6525,62.605,67.12,66.72,...,90.25,78.565,71.03,82.595,93.315,88.535,87.94,86.5,83.755,77.53

In [9]:
new_cols = [date[:-3] for date in df_price.columns]
#new_cols

In [10]:
df_price.columns = new_cols
df_price

,2019-05,2019-04,2019-03,2019-02,2019-01,2018-12,2018-11,2018-10,2018-09,2018-08,...,1998-11,1998-10,1998-09,1998-08,1998-07,1998-06,1998-05,1998-04,1998-03,1998-02
2. high,72.47,72.85,68.60690,67.470,64.850,65.8800,63.9850,67.800,69.29,68.43,...,95.00,90.000,77.00,93.310,98.880,92.130,91.00,91.5,88.880,81.81
3. low,69.55,67.25,64.78000,64.200,58.620,57.5050,59.3200,57.410,64.95,65.01,...,85.50,67.130,65.06,71.880,87.750,84.940,84.88,81.5,78.630,73.25
mean,71.01,70.05,66.69345,65.835,61.735,61.6925,61.6525,62.605,67.12,66.72,...,90.25,78.565,71.03,82.595,93.315,88.535,87.94,86.5,83.755,77.53

In [11]:
#df_price.replace("","country")
df_price.rename(columns= {"": "Country"}, inplace=True)
df_price

,2019-05,2019-04,2019-03,2019-02,2019-01,2018-12,2018-11,2018-10,2018-09,2018-08,...,1998-11,1998-10,1998-09,1998-08,1998-07,1998-06,1998-05,1998-04,1998-03,1998-02
2. high,72.47,72.85,68.60690,67.470,64.850,65.8800,63.9850,67.800,69.29,68.43,...,95.00,90.000,77.00,93.310,98.880,92.130,91.00,91.5,88.880,81.81
3. low,69.55,67.25,64.78000,64.200,58.620,57.5050,59.3200,57.410,64.95,65.01,...,85.50,67.130,65.06,71.880,87.750,84.940,84.88,81.5,78.630,73.25
mean,71.01,70.05,66.69345,65.835,61.735,61.6925,61.6525,62.605,67.12,66.72,...,90.25,78.565,71.03,82.595,93.315,88.535,87.94,86.5,83.755,77.53

In [12]:
csv_file = "JODI Data.csv"
df_production = pd.read_csv(csv_file, skiprows=4)
df_production

,Time,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
0,Country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,Algeria,1269.0000,1217.0000,1204.0000,1204.0000,1204.0000,1217.0000,1216.0000,1197.0000,1188.0000,...,1040.0000,1054.0000,1064.0000,1062.0000,1072.0000,1070.0000,1068.0000,1063.0000,1033.0000,0.0000
3,Angola,1600.0000,1446.0000,1599.0000,1605.0000,1645.0000,1714.0000,1709.0000,1703.0000,1751.0000,...,1486.0000,1448.0000,1455.0000,1481.0000,1489.0000,1457.0000,1417.0000,1445.0000,1470.0000,1423.0000
4,Argentina,534.2857,531.1935,511.3000,501.0645,532.3333,522.0645,525.4194,528.8667,535.2258,...,481.7742,481.7000,480.4194,487.9677,495.3667,495.0323,492.6667,493.0968,493.0968,0.0000
5,Armenia,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
6,Australia,359.0491,341.3442,321.4452,313.6195,348.7798,335.7484,352.0271,336.1638,347.4487,...,238.3305,269.1413,274.4489,263.5116,280.9688,296.0690,300.1557,310.5673,302.6823,323.5666
7,Austria,17.3560,18.6299,17.6075,18.1755,16.6684,17.0395,16.5851,16.4337,16.5851,...,13.4044,13.3817,12.9500,12.7228,13.6165,13.1772,13.3817,12.2685,12.7228,13.5829
8,Azerbaijan,803.8564,807.8471,836.2493,827.3419,801.3647,827.5797,814.5039,796.9427,798.8129,...,737.0000,728.1560,718.4561,710.3729,715.6270,707.0445,723.9797,712.0371,710.8484,715.9429
9,Bahrain,49.4843,50.6390,48.6420,49.4503,48.8877,49.9258,50.4013,50.1160,48.4994,...,209.9261,206.6057,208.9752,206.1223,203.6577,205.8845,201.4467,195.4239,190.4313,204.5175
10,Bangladesh,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
11,Barbados,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
12,Belarus,33.3693,33.4625,33.1065,33.2252,33.8422,32.9878,33.2252,32.6160,33.2252,...,33.9371,34.3327,33.2252,33.2252,34.3327,34.4118,33.5970,32.9878,33.4625,0.0000
13,Belgium,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
14,Belize,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
15,Bermuda,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
16,Bolivia,65.3214,62.1935,63.4333,65.2258,64.8333,65.1935,63.5806,63.4000,62.5161,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
17,Brazil,2096.2500,2124.2258,2152.7667,2195.0968,2251.5000,2272.2581,2332.2258,2364.4333,2398.0000,...,2615.8710,2598.9000,2583.3226,2525.4516,2489.4667,2618.0323,2571.4333,2694.6452,2634.9677,2493.7500
18,Brunei Darussalam,131.1991,130.8475,119.4599,108.7963,123.2505,108.4692,90.6801,107.2889,109.1866,...,84.7638,102.5859,94.4152,94.6867,92.8239,102.9708,103.1830,112.4507,113.6741,116.8405
19,Bulgaria,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
20,Canada,2686.0893,2831.2361,2787.2760,2768.4690,2739.4093,2761.7523,2782.1342,2735.1013,2887.5181,...,3660.4103,3562.9553,3746.5703,3867.0090,3711.1027,3782.0071,3719.2400,3815.5910,3554.7948,3947.4614
21,Chile,6.7404,6.7645,6.2910,6.7645,5.8250,6.0881,6.3135,6.5240,5.4116,...,2.7058,3.0290,2.9313,2.9313,2.7960,2.7058,2.7960,2.7058,2.9313,3.2454
22,China,4212.6600,4164.8439,4142.8760,4192.7071,4270.4880,4094.9497,4129.4245,4186.7960,4235.2103,...,3771.6890,3866.4240,3743.8258,3777.3561,3702.9440,3799.0800,3790.2960,3856.6955,0.0000,0.0000
23,Chinese Taipei,0.1725,0.2352,0.1505,0.1023,0.1205,0.1252,0.1473,0.1572,0.1704,...,0.0631,0.0843,0.0682,0.0688,0.0730,0.0712,0.0876,0.1157,0.0735,0.0800
24,Colombia,1003.9643,979.0323,938.3667,951.9355,1011.1333,971.0000,1001.9355,995.7667,1004.3548,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25,Costa Rica,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
26,Croatia,10.5971,11.0074,10.8797,10.5288,10.6325,10.2895,10.5288,9.8907,11.0074,...,13.8788,13.8469,13.1610,14.3574,14.0942,13.8788,14.0942,13.8788,13.8788,13.7763
27,Cuba,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
28,Cyprus,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
29,Czech Republic,2.8796,2.8374,3.1763,3.3103,3.1763,3.0739,3.0739,3.1763,3.0739,...,2.6010,2.4433,2.3645,2.3645,2.1990,2.1281,1.9547,2.1281,1.8916,1.8325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Peru,70.4482,73.5046,67.3785,69.3688,72.0430,68.3385,68.5597,69.5876,71.5283,...,52.2009,41.5259,42.8787,44.1349,52.0277,0.0000,0.0000,0.0000,0.0000,0.0000
86,Philippines,10.3643,19.0194,20.6867,10.3871,11.2667,9.5806,11.1930,11.0380,0.4903,...,31.6903,9.9833,10.8387,12.1290,10.2333,10.4677,9.1667,10.5484,13.7097,0.0000
87,Poland,19.1104,20.5713,19.7910,20.8077,13.6827,19.6255,14.8965,20.5240,20.0984,...,20.5713,14.1713,21.5171,21.2806,17.5920,21.9900,21.2570,20.8077,20.5713,21.4664
88,Portugal,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
89,Qatar,734.0000,710.0000,701.0000,701.0000,729.0000,734.0000,734.0000,690.0000,680.0000,...,601.0000,622.0000,619.0000,612.0000,570.0000,609.0000,599.0000,615.0000,0.0000,0.0000
90,Romania,82.0189,82.0708,80.8038,80.8603,80.8038,79.1656,79.4077,80.0533,79.8919,...,71.6606,71.0473,69.4818,70.9344,70.5470,70.4502,70.5470,70.4502,70.4502,70.4934
91,Russian Federation,10061.9571,10037.3806,10053.2000,10084.8387,10126.7600,10037.3806,10061.1097,10151.2800,10084.8387,...,10345.8581,10472.0722,10654.3355,10654.3355,10739.7600,10749.2516,10728.7709,10726.4136,10673.6049,10669.4979
92,Saudi Arabia,9850.0000,9566.0000,9660.0000,9705.0000,9780.0000,10005.0000,9597.0000,9704.0000,9690.0000,...,10030.0000,10489.0000,10288.0000,10412.0000,10502.0000,10642.0000,11093.0000,10643.0000,10243.0000,10136.0000
93,Singapore,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
94,Slovakia,0.2618,0.2365,0.2443,0.2365,0.2443,0.2365,0.2365,0.2443,0.2365,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.2365,0.2443,0.0000,0.0000,0.2618
95,Slovenia,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
96,South Africa,5.1789,1.1006,2.5590,5.2281,2.8433,2.2013,2.2013,5.4023,2.4765,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
97,Spain,7.1743,6.7200,7.6880,7.6800,6.9440,6.7200,6.9600,3.7200,6.0000,...,1.9200,1.9840,1.9200,1.4400,1.7360,1.2000,1.7360,1.4400,0.9600,1.0629
98,Suriname,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
99,Sweden,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
100,Switzerland,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
101,Syria (Arab Rep.),0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
102,Tajikistan,0.2632,0.4755,0.4913,0.4755,0.2457,0.4755,0.4755,0.4913,0.2377,...,0.4755,0.4913,0.2377,0.4755,0.4913,0.2377,0.2457,0.2377,0.0000,0.0000
103,Thailand,233.2482,233.7176,227.7078,243.3393,239.7050,227.8374,232.3784,234.4424,226.1817,...,228.9737,225.0304,213.2932,213.2932,217.6417,236.0895,234.3040,223.2640,207.9183,0.0000
104,Trinidad/Tobago,81.6786,82.3226,80.1333,79.4516,81.5333,82.4194,82.1935,83.3333,86.0323,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
105,Tunisia,59.3229,58.7913,54.8553,49.3648,55.1117,54.5742,54.8223,50.4977,52.5897,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
106,Turkey,45.6950,45.8084,46.6323,48.5297,48.9757,47.1690,47.8494,50.6160,47.6226,...,54.8794,54.8340,56.9203,56.6935,56.4743,56.4668,57.6460,55.7865,54.4258,60.5082
107,Ukraine,42.9039,42.3181,42.5003,42.0803,41.7633,40.6539,39.7029,41.0263,40.1784,...,32.3329,32.6737,33.0461,32.8084,32.4280,33.0461,32.9193,32.8084,33.7594,0.0000
108,United Arab Emirates,3043.0000,3003.0000,2830.0000,3090.0000,3108.0000,3148.0000,3171.0000,3072.0000,2908.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
109,United Kingdom,913.1400,892.5677,803.8800,856.2310,739.3680,690.1548,465.3058,744.4080,790.1419,...,973.0452,935.9280,996.9445,924.2710,885.7800,1024.9897,1018.8360,1068.8865,1051.0839,1140.4800
110,United States of America,8135.8214,8274.4194,8572.7333,8612.3226,8717.5000,8782.3548,8885.6774,9040.8333,9220.5161,...,10463.9032,10672.3667,10935.9677,11325.0000,11470.4667,11558.9677,11926.0667,11961.0323,11870.7419,12025.0000
111,Uruguay,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
112,Venezuela,2677.0000,2677.0000,2691.0000,2690.0000,2676.0000,2696.0000,2664.0000,2644.0000,2675.0000,...,1533.0000,1531.0000,1469.0000,1448.0000,1434.0000,1433.0000,1464.0000,1511.0000,1489.0000,1432.0000
113,Vietnam,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
114,Yemen,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [13]:
df_production=df_production.dropna(axis=0)
df_production.head()

,Time,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
1,Albania,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0
2,Algeria,1269.0000,1217.0000,1204.0,1204.0000,1204.0000,1217.0000,1216.0000,1197.0000,1188.0000,...,1040.0000,1054.0,1064.0000,1062.0000,1072.0000,1070.0000,1068.0000,1063.0000,1033.0000,0.0
3,Angola,1600.0000,1446.0000,1599.0,1605.0000,1645.0000,1714.0000,1709.0000,1703.0000,1751.0000,...,1486.0000,1448.0,1455.0000,1481.0000,1489.0000,1457.0000,1417.0000,1445.0000,1470.0000,1423.0
4,Argentina,534.2857,531.1935,511.3,501.0645,532.3333,522.0645,525.4194,528.8667,535.2258,...,481.7742,481.7,480.4194,487.9677,495.3667,495.0323,492.6667,493.0968,493.0968,0.0
5,Armenia,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0

In [14]:
df_production.reset_index(drop=True,inplace=True)
df_production.rename(columns=
              {"Time": "Country"},inplace=True)
df_production.head()

C:\Users\hocin\Anaconda\Anaconda3\lib\site-packages\pandas\core\frame.py:3781: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

,Country,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
0,Albania,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0
1,Algeria,1269.0000,1217.0000,1204.0,1204.0000,1204.0000,1217.0000,1216.0000,1197.0000,1188.0000,...,1040.0000,1054.0,1064.0000,1062.0000,1072.0000,1070.0000,1068.0000,1063.0000,1033.0000,0.0
2,Angola,1600.0000,1446.0000,1599.0,1605.0000,1645.0000,1714.0000,1709.0000,1703.0000,1751.0000,...,1486.0000,1448.0,1455.0000,1481.0000,1489.0000,1457.0000,1417.0000,1445.0000,1470.0000,1423.0
3,Argentina,534.2857,531.1935,511.3,501.0645,532.3333,522.0645,525.4194,528.8667,535.2258,...,481.7742,481.7,480.4194,487.9677,495.3667,495.0323,492.6667,493.0968,493.0968,0.0
4,Armenia,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0

In [15]:
df_production.set_index('Country', inplace=True)
df_production

,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
Country,,,,,,,,,,,,,,,,,,,,,
Albania,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Algeria,1269.0000,1217.0000,1204.0000,1204.0000,1204.0000,1217.0000,1216.0000,1197.0000,1188.0000,1204.0000,...,1040.0000,1054.0000,1064.0000,1062.0000,1072.0000,1070.0000,1068.0000,1063.0000,1033.0000,0.0000
Angola,1600.0000,1446.0000,1599.0000,1605.0000,1645.0000,1714.0000,1709.0000,1703.0000,1751.0000,1691.0000,...,1486.0000,1448.0000,1455.0000,1481.0000,1489.0000,1457.0000,1417.0000,1445.0000,1470.0000,1423.0000
Argentina,534.2857,531.1935,511.3000,501.0645,532.3333,522.0645,525.4194,528.8667,535.2258,530.2667,...,481.7742,481.7000,480.4194,487.9677,495.3667,495.0323,492.6667,493.0968,493.0968,0.0000
Armenia,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Australia,359.0491,341.3442,321.4452,313.6195,348.7798,335.7484,352.0271,336.1638,347.4487,361.1330,...,238.3305,269.1413,274.4489,263.5116,280.9688,296.0690,300.1557,310.5673,302.6823,323.5666
Austria,17.3560,18.6299,17.6075,18.1755,16.6684,17.0395,16.5851,16.4337,16.5851,16.9032,...,13.4044,13.3817,12.9500,12.7228,13.6165,13.1772,13.3817,12.2685,12.7228,13.5829
Azerbaijan,803.8564,807.8471,836.2493,827.3419,801.3647,827.5797,814.5039,796.9427,798.8129,625.4673,...,737.0000,728.1560,718.4561,710.3729,715.6270,707.0445,723.9797,712.0371,710.8484,715.9429
Bahrain,49.4843,50.6390,48.6420,49.4503,48.8877,49.9258,50.4013,50.1160,48.4994,50.3617,...,209.9261,206.6057,208.9752,206.1223,203.6577,205.8845,201.4467,195.4239,190.4313,204.5175
Bangladesh,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Barbados,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Belarus,33.3693,33.4625,33.1065,33.2252,33.8422,32.9878,33.2252,32.6160,33.2252,32.8613,...,33.9371,34.3327,33.2252,33.2252,34.3327,34.4118,33.5970,32.9878,33.4625,0.0000
Belgium,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Belize,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Bermuda,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Bolivia,65.3214,62.1935,63.4333,65.2258,64.8333,65.1935,63.5806,63.4000,62.5161,58.1333,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Brazil,2096.2500,2124.2258,2152.7667,2195.0968,2251.5000,2272.2581,2332.2258,2364.4333,2398.0000,2363.3333,...,2615.8710,2598.9000,2583.3226,2525.4516,2489.4667,2618.0323,2571.4333,2694.6452,2634.9677,2493.7500
Brunei Darussalam,131.1991,130.8475,119.4599,108.7963,123.2505,108.4692,90.6801,107.2889,109.1866,107.6704,...,84.7638,102.5859,94.4152,94.6867,92.8239,102.9708,103.1830,112.4507,113.6741,116.8405
Bulgaria,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Canada,2686.0893,2831.2361,2787.2760,2768.4690,2739.4093,2761.7523,2782.1342,2735.1013,2887.5181,2788.7120,...,3660.4103,3562.9553,3746.5703,3867.0090,3711.1027,3782.0071,3719.2400,3815.5910,3554.7948,3947.4614
Chile,6.7404,6.7645,6.2910,6.7645,5.8250,6.0881,6.3135,6.5240,5.4116,5.1260,...,2.7058,3.0290,2.9313,2.9313,2.7960,2.7058,2.7960,2.7058,2.9313,3.2454
China,4212.6600,4164.8439,4142.8760,4192.7071,4270.4880,4094.9497,4129.4245,4186.7960,4235.2103,4301.7200,...,3771.6890,3866.4240,3743.8258,3777.3561,3702.9440,3799.0800,3790.2960,3856.6955,0.0000,0.0000
Chinese Taipei,0.1725,0.2352,0.1505,0.1023,0.1205,0.1252,0.1473,0.1572,0.1704,0.1445,...,0.0631,0.0843,0.0682,0.0688,0.0730,0.0712,0.0876,0.1157,0.0735,0.0800
Colombia,1003.9643,979.0323,938.3667,951.9355,1011.1333,971.0000,1001.9355,995.7667,1004.3548,1003.9333,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Costa Rica,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Croatia,10.5971,11.0074,10.8797,10.5288,10.6325,10.2895,10.5288,9.8907,11.0074,11.6215,...,13.8788,13.8469,13.1610,14.3574,14.0942,13.8788,14.0942,13.8788,13.8788,13.7763
Cuba,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Cyprus,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Czech Republic,2.8796,2.8374,3.1763,3.3103,3.1763,3.0739,3.0739,3.1763,3.0739,2.9320,...,2.6010,2.4433,2.3645,2.3645,2.1990,2.1281,1.9547,2.1281,1.8916,1.8325
Denmark,168.3500,164.9484,162.5533,171.8710,108.7800,159.2194,174.0194,163.5400,174.7355,187.9600,...,114.8194,106.0667,122.9355,68.9871,122.8400,121.5032,125.5533,125.3226,108.1355,116.5500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Peru,70.4482,73.5046,67.3785,69.3688,72.0430,68.3385,68.5597,69.5876,71.5283,69.8910,...,52.2009,41.5259,42.8787,44.1349,52.0277,0.0000,0.0000,0.0000,0.0000,0.0000
Philippines,10.3643,19.0194,20.6867,10.3871,11.2667,9.5806,11.1930,11.0380,0.4903,11.8000,...,31.6903,9.9833,10.8387,12.1290,10.2333,10.4677,9.1667,10.5484,13.7097,0.0000
Poland,19.1104,20.5713,19.7910,20.8077,13.6827,19.6255,14.8965,20.5240,20.0984,20.0353,...,20.5713,14.1713,21.5171,21.2806,17.5920,21.9900,21.2570,20.8077,20.5713,21.4664
Portugal,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Qatar,734.0000,710.0000,701.0000,701.0000,729.0000,734.0000,734.0000,690.0000,680.0000,681.0000,...,601.0000,622.0000,619.0000,612.0000,570.0000,609.0000,599.0000,615.0000,0.0000,0.0000
Romania,82.0189,82.0708,80.8038,80.8603,80.8038,79.1656,79.4077,80.0533,79.8919,79.0527,...,71.6606,71.0473,69.4818,70.9344,70.5470,70.4502,70.5470,70.4502,70.4502,70.4934
Russian Federation,10061.9571,10037.3806,10053.2000,10084.8387,10126.7600,10037.3806,10061.1097,10151.2800,10084.8387,10151.2800,...,10345.8581,10472.0722,10654.3355,10654.3355,10739.7600,10749.2516,10728.7709,10726.4136,10673.6049,10669.4979
Saudi Arabia,9850.0000,9566.0000,9660.0000,9705.0000,9780.0000,10005.0000,9597.0000,9704.0000,9690.0000,9610.0000,...,10030.0000,10489.0000,10288.0000,10412.0000,10502.0000,10642.0000,11093.0000,10643.0000,10243.0000,10136.0000
Singapore,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Slovakia,0.2618,0.2365,0.2443,0.2365,0.2443,0.2365,0.2365,0.2443,0.2365,0.2443,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.2365,0.2443,0.0000,0.0000,0.2618
Slovenia,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
South Africa,5.1789,1.1006,2.5590,5.2281,2.8433,2.2013,2.2013,5.4023,2.4765,5.6867,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Spain,7.1743,6.7200,7.6880,7.6800,6.9440,6.7200,6.9600,3.7200,6.0000,4.2160,...,1.9200,1.9840,1.9200,1.4400,1.7360,1.2000,1.7360,1.4400,0.9600,1.0629
Suriname,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Sweden,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Switzerland,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Syria (Arab Rep.),0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Tajikistan,0.2632,0.4755,0.4913,0.4755,0.2457,0.4755,0.4755,0.4913,0.2377,0.4913,...,0.4755,0.4913,0.2377,0.4755,0.4913,0.2377,0.2457,0.2377,0.0000,0.0000
Thailand,233.2482,233.7176,227.7078,243.3393,239.7050,227.8374,232.3784,234.4424,226.1817,240.4598,...,228.9737,225.0304,213.2932,213.2932,217.6417,236.0895,234.3040,223.2640,207.9183,0.0000
Trinidad/Tobago,81.6786,82.3226,80.1333,79.4516,81.5333,82.4194,82.1935,83.3333,86.0323,78.7000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Tunisia,59.3229,58.7913,54.8553,49.3648,55.1117,54.5742,54.8223,50.4977,52.5897,53.3173,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Turkey,45.6950,45.8084,46.6323,48.5297,48.9757,47.1690,47.8494,50.6160,47.6226,46.6323,...,54.8794,54.8340,56.9203,56.6935,56.4743,56.4668,57.6460,55.7865,54.4258,60.5082
Ukraine,42.9039,42.3181,42.5003,42.0803,41.7633,40.6539,39.7029,41.0263,40.1784,39.0610,...,32.3329,32.6737,33.0461,32.8084,32.4280,33.0461,32.9193,32.8084,33.7594,0.0000
United Arab Emirates,3043.0000,3003.0000,2830.0000,3090.0000,3108.0000,3148.0000,3171.0000,3072.0000,2908.0000,2938.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
United Kingdom,913.1400,892.5677,803.8800,856.2310,739.3680,690.1548,465.3058,744.4080,790.1419,791.0280,...,973.0452,935.9280,996.9445,924.2710,885.7800,1024.9897,1018.8360,1068.8865,1051.0839,1140.4800
United States of America,8135.8214,8274.4194,8572.7333,8612.3226,8717.5000,8782.3548,8885.6774,9040.8333,9220.5161,9302.7667,...,10463.9032,10672.3667,10935.9677,11325.0000,11470.4667,11558.9677,11926.0667,11961.0323,11870.7419,12025.0000
Uruguay,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Venezuela,2677.0000,2677.0000,2691.0000,2690.0000,2676.0000,2696.0000,2664.0000,2644.0000,2675.0000,2695.0000,...,1533.0000,1531.0000,1469.0000,1448.0000,1434.0000,1433.0000,1464.0000,1511.0000,1489.0000,1432.0000
Vietnam,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Yemen,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [16]:
frames = [df_price,df_production]
df_data = pd.concat(frames)

df_data

C:\Users\hocin\Anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,1998-02,1998-03,1998-04,1998-05,1998-06,1998-07,1998-08,1998-09,1998-10,1998-11,...,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05
2. high,81.81,88.880,91.5,91.00,92.130,98.880,93.310,77.00,90.000,95.00,...,68.4300,69.2900,67.8000,63.9850,65.8800,64.8500,67.4700,68.60690,72.85,72.47
3. low,73.25,78.630,81.5,84.88,84.940,87.750,71.880,65.06,67.130,85.50,...,65.0100,64.9500,57.4100,59.3200,57.5050,58.6200,64.2000,64.78000,67.25,69.55
mean,77.53,83.755,86.5,87.94,88.535,93.315,82.595,71.03,78.565,90.25,...,66.7200,67.1200,62.6050,61.6525,61.6925,61.7350,65.8350,66.69345,70.05,71.01
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1062.0000,1072.0000,1070.0000,1068.0000,1063.0000,1033.0000,0.0000,NaN,NaN,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1481.0000,1489.0000,1457.0000,1417.0000,1445.0000,1470.0000,1423.0000,NaN,NaN,NaN
Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,487.9677,495.3667,495.0323,492.6667,493.0968,493.0968,0.0000,NaN,NaN,NaN
Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,263.5116,280.9688,296.0690,300.1557,310.5673,302.6823,323.5666,NaN,NaN,NaN
Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.7228,13.6165,13.1772,13.3817,12.2685,12.7228,13.5829,NaN,NaN,NaN
Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,710.3729,715.6270,707.0445,723.9797,712.0371,710.8484,715.9429,NaN,NaN,NaN
Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,206.1223,203.6577,205.8845,201.4467,195.4239,190.4313,204.5175,NaN,NaN,NaN
Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.2252,34.3327,34.4118,33.5970,32.9878,33.4625,0.0000,NaN,NaN,NaN
Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Bermuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2525.4516,2489.4667,2618.0323,2571.4333,2694.6452,2634.9677,2493.7500,NaN,NaN,NaN
Brunei Darussalam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94.6867,92.8239,102.9708,103.1830,112.4507,113.6741,116.8405,NaN,NaN,NaN
Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3867.0090,3711.1027,3782.0071,3719.2400,3815.5910,3554.7948,3947.4614,NaN,NaN,NaN
Chile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.9313,2.7960,2.7058,2.7960,2.7058,2.9313,3.2454,NaN,NaN,NaN
China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3777.3561,3702.9440,3799.0800,3790.2960,3856.6955,0.0000,0.0000,NaN,NaN,NaN
Chinese Taipei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0688,0.0730,0.0712,0.0876,0.1157,0.0735,0.0800,NaN,NaN,NaN
Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Costa Rica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.3574,14.0942,13.8788,14.0942,13.8788,13.8788,13.7763,NaN,NaN,NaN
Cuba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Peru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.1349,52.0277,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Philippines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.1290,10.2333,10.4677,9.1667,10.5484,13.7097,0.0000,NaN,NaN,NaN
Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.2806,17.5920,21.9900,21.2570,20.8077,20.5713,21.4664,NaN,NaN,NaN
Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Qatar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,612.0000,570.0000,609.0000,599.0000,615.0000,0.0000,0.0000,NaN,NaN,NaN
Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.9344,70.5470,70.4502,70.5470,70.4502,70.4502,70.4934,NaN,NaN,NaN
Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10654.3355,10739.7600,10749.2516,10728.7709,10726.4136,10673.6049,10669.4979,NaN,NaN,NaN
Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10412.0000,10502.0000,10642.0000,11093.0000,10643.0000,10243.0000,10136.0000,NaN,NaN,NaN
Singapore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Slovakia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.2365,0.2443,0.0000,0.0000,0.2618,NaN,NaN,NaN
Slovenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.4400,1.7360,1.2000,1.7360,1.4400,0.9600,1.0629,NaN,NaN,NaN
Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Sweden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Syria (Arab Rep.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Tajikistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.4755,0.4913,0.2377,0.2457,0.2377,0.0000,0.0000,NaN,NaN,NaN
Thailand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,213.2932,217.6417,236.0895,234.3040,223.2640,207.9183,0.0000,NaN,NaN,NaN
Trinidad/Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Tunisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.6935,56.4743,56.4668,57.6460,55.7865,54.4258,60.5082,NaN,NaN,NaN
Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.8084,32.4280,33.0461,32.9193,32.8084,33.7594,0.0000,NaN,NaN,NaN
United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
United Kingdom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,924.2710,885.7800,1024.9897,1018.8360,1068.8865,1051.0839,1140.4800,NaN,NaN,NaN
United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11325.0000,11470.4667,11558.9677,11926.0667,11961.0323,11870.7419,12025.0000,NaN,NaN,NaN
Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1448.0000,1434.0000,1433.0000,1464.0000,1511.0000,1489.0000,1432.0000,NaN,NaN,NaN
Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN

In [17]:
df_data = df_data.dropna(axis = 1)
df_data

,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
2. high,63.1500,65.9200,67.9500,69.8050,69.4700,70.1100,65.7000,66.3600,67.1200,69.9000,...,65.3900,65.6650,67.9200,68.4300,69.2900,67.8000,63.9850,65.8800,64.8500,67.4700
3. low,59.7500,62.0000,63.8700,66.1000,66.9800,63.4000,62.8900,63.3600,62.5300,66.7100,...,61.2800,61.9700,64.0300,65.0100,64.9500,57.4100,59.3200,57.5050,58.6200,64.2000
mean,61.4500,63.9600,65.9100,67.9525,68.2250,66.7550,64.2950,64.8600,64.8250,68.3050,...,63.3350,63.8175,65.9750,66.7200,67.1200,62.6050,61.6525,61.6925,61.7350,65.8350
Albania,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Algeria,1269.0000,1217.0000,1204.0000,1204.0000,1204.0000,1217.0000,1216.0000,1197.0000,1188.0000,1204.0000,...,1040.0000,1054.0000,1064.0000,1062.0000,1072.0000,1070.0000,1068.0000,1063.0000,1033.0000,0.0000
Angola,1600.0000,1446.0000,1599.0000,1605.0000,1645.0000,1714.0000,1709.0000,1703.0000,1751.0000,1691.0000,...,1486.0000,1448.0000,1455.0000,1481.0000,1489.0000,1457.0000,1417.0000,1445.0000,1470.0000,1423.0000
Argentina,534.2857,531.1935,511.3000,501.0645,532.3333,522.0645,525.4194,528.8667,535.2258,530.2667,...,481.7742,481.7000,480.4194,487.9677,495.3667,495.0323,492.6667,493.0968,493.0968,0.0000
Armenia,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Australia,359.0491,341.3442,321.4452,313.6195,348.7798,335.7484,352.0271,336.1638,347.4487,361.1330,...,238.3305,269.1413,274.4489,263.5116,280.9688,296.0690,300.1557,310.5673,302.6823,323.5666
Austria,17.3560,18.6299,17.6075,18.1755,16.6684,17.0395,16.5851,16.4337,16.5851,16.9032,...,13.4044,13.3817,12.9500,12.7228,13.6165,13.1772,13.3817,12.2685,12.7228,13.5829
Azerbaijan,803.8564,807.8471,836.2493,827.3419,801.3647,827.5797,814.5039,796.9427,798.8129,625.4673,...,737.0000,728.1560,718.4561,710.3729,715.6270,707.0445,723.9797,712.0371,710.8484,715.9429
Bahrain,49.4843,50.6390,48.6420,49.4503,48.8877,49.9258,50.4013,50.1160,48.4994,50.3617,...,209.9261,206.6057,208.9752,206.1223,203.6577,205.8845,201.4467,195.4239,190.4313,204.5175
Bangladesh,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Barbados,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Belarus,33.3693,33.4625,33.1065,33.2252,33.8422,32.9878,33.2252,32.6160,33.2252,32.8613,...,33.9371,34.3327,33.2252,33.2252,34.3327,34.4118,33.5970,32.9878,33.4625,0.0000
Belgium,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Belize,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Bermuda,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Bolivia,65.3214,62.1935,63.4333,65.2258,64.8333,65.1935,63.5806,63.4000,62.5161,58.1333,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Brazil,2096.2500,2124.2258,2152.7667,2195.0968,2251.5000,2272.2581,2332.2258,2364.4333,2398.0000,2363.3333,...,2615.8710,2598.9000,2583.3226,2525.4516,2489.4667,2618.0323,2571.4333,2694.6452,2634.9677,2493.7500
Brunei Darussalam,131.1991,130.8475,119.4599,108.7963,123.2505,108.4692,90.6801,107.2889,109.1866,107.6704,...,84.7638,102.5859,94.4152,94.6867,92.8239,102.9708,103.1830,112.4507,113.6741,116.8405
Bulgaria,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Canada,2686.0893,2831.2361,2787.2760,2768.4690,2739.4093,2761.7523,2782.1342,2735.1013,2887.5181,2788.7120,...,3660.4103,3562.9553,3746.5703,3867.0090,3711.1027,3782.0071,3719.2400,3815.5910,3554.7948,3947.4614
Chile,6.7404,6.7645,6.2910,6.7645,5.8250,6.0881,6.3135,6.5240,5.4116,5.1260,...,2.7058,3.0290,2.9313,2.9313,2.7960,2.7058,2.7960,2.7058,2.9313,3.2454
China,4212.6600,4164.8439,4142.8760,4192.7071,4270.4880,4094.9497,4129.4245,4186.7960,4235.2103,4301.7200,...,3771.6890,3866.4240,3743.8258,3777.3561,3702.9440,3799.0800,3790.2960,3856.6955,0.0000,0.0000
Chinese Taipei,0.1725,0.2352,0.1505,0.1023,0.1205,0.1252,0.1473,0.1572,0.1704,0.1445,...,0.0631,0.0843,0.0682,0.0688,0.0730,0.0712,0.0876,0.1157,0.0735,0.0800
Colombia,1003.9643,979.0323,938.3667,951.9355,1011.1333,971.0000,1001.9355,995.7667,1004.3548,1003.9333,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Costa Rica,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Croatia,10.5971,11.0074,10.8797,10.5288,10.6325,10.2895,10.5288,9.8907,11.0074,11.6215,...,13.8788,13.8469,13.1610,14.3574,14.0942,13.8788,14.0942,13.8788,13.8788,13.7763
Cuba,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Peru,70.4482,73.5046,67.3785,69.3688,72.0430,68.3385,68.5597,69.5876,71.5283,69.8910,...,52.2009,41.5259,42.8787,44.1349,52.0277,0.0000,0.0000,0.0000,0.0000,0.0000
Philippines,10.3643,19.0194,20.6867,10.3871,11.2667,9.5806,11.1930,11.0380,0.4903,11.8000,...,31.6903,9.9833,10.8387,12.1290,10.2333,10.4677,9.1667,10.5484,13.7097,0.0000
Poland,19.1104,20.5713,19.7910,20.8077,13.6827,19.6255,14.8965,20.5240,20.0984,20.0353,...,20.5713,14.1713,21.5171,21.2806,17.5920,21.9900,21.2570,20.8077,20.5713,21.4664
Portugal,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Qatar,734.0000,710.0000,701.0000,701.0000,729.0000,734.0000,734.0000,690.0000,680.0000,681.0000,...,601.0000,622.0000,619.0000,612.0000,570.0000,609.0000,599.0000,615.0000,0.0000,0.0000
Romania,82.0189,82.0708,80.8038,80.8603,80.8038,79.1656,79.4077,80.0533,79.8919,79.0527,...,71.6606,71.0473,69.4818,70.9344,70.5470,70.4502,70.5470,70.4502,70.4502,70.4934
Russian Federation,10061.9571,10037.3806,10053.2000,10084.8387,10126.7600,10037.3806,10061.1097,10151.2800,10084.8387,10151.2800,...,10345.8581,10472.0722,10654.3355,10654.3355,10739.7600,10749.2516,10728.7709,10726.4136,10673.6049,10669.4979
Saudi Arabia,9850.0000,9566.0000,9660.0000,9705.0000,9780.0000,10005.0000,9597.0000,9704.0000,9690.0000,9610.0000,...,10030.0000,10489.0000,10288.0000,10412.0000,10502.0000,10642.0000,11093.0000,10643.0000,10243.0000,10136.0000
Singapore,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Slovakia,0.2618,0.2365,0.2443,0.2365,0.2443,0.2365,0.2365,0.2443,0.2365,0.2443,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.2365,0.2443,0.0000,0.0000,0.2618
Slovenia,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
South Africa,5.1789,1.1006,2.5590,5.2281,2.8433,2.2013,2.2013,5.4023,2.4765,5.6867,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Spain,7.1743,6.7200,7.6880,7.6800,6.9440,6.7200,6.9600,3.7200,6.0000,4.2160,...,1.9200,1.9840,1.9200,1.4400,1.7360,1.2000,1.7360,1.4400,0.9600,1.0629
Suriname,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Sweden,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Switzerland,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Syria (Arab Rep.),0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Tajikistan,0.2632,0.4755,0.4913,0.4755,0.2457,0.4755,0.4755,0.4913,0.2377,0.4913,...,0.4755,0.4913,0.2377,0.4755,0.4913,0.2377,0.2457,0.2377,0.0000,0.0000
Thailand,233.2482,233.7176,227.7078,243.3393,239.7050,227.8374,232.3784,234.4424,226.1817,240.4598,...,228.9737,225.0304,213.2932,213.2932,217.6417,236.0895,234.3040,223.2640,207.9183,0.0000
Trinidad/Tobago,81.6786,82.3226,80.1333,79.4516,81.5333,82.4194,82.1935,83.3333,86.0323,78.7000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Tunisia,59.3229,58.7913,54.8553,49.3648,55.1117,54.5742,54.8223,50.4977,52.5897,53.3173,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Turkey,45.6950,45.8084,46.6323,48.5297,48.9757,47.1690,47.8494,50.6160,47.6226,46.6323,...,54.8794,54.8340,56.9203,56.6935,56.4743,56.4668,57.6460,55.7865,54.4258,60.5082
Ukraine,42.9039,42.3181,42.5003,42.0803,41.7633,40.6539,39.7029,41.0263,40.1784,39.0610,...,32.3329,32.6737,33.0461,32.8084,32.4280,33.0461,32.9193,32.8084,33.7594,0.0000
United Arab Emirates,3043.0000,3003.0000,2830.0000,3090.0000,3108.0000,3148.0000,3171.0000,3072.0000,2908.0000,2938.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
United Kingdom,913.1400,892.5677,803.8800,856.2310,739.3680,690.1548,465.3058,744.4080,790.1419,791.0280,...,973.0452,935.9280,996.9445,924.2710,885.7800,1024.9897,1018.8360,1068.8865,1051.0839,1140.4800
United States of America,8135.8214,8274.4194,8572.7333,8612.3226,8717.5000,8782.3548,8885.6774,9040.8333,9220.5161,9302.7667,...,10463.9032,10672.3667,10935.9677,11325.0000,11470.4667,11558.9677,11926.0667,11961.0323,11870.7419,12025.0000
Uruguay,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Venezuela,2677.0000,2677.0000,2691.0000,2690.0000,2676.0000,2696.0000,2664.0000,2644.0000,2675.0000,2695.0000,...,1533.0000,1531.0000,1469.0000,1448.0000,1434.0000,1433.0000,1464.0000,1511.0000,1489.0000,1432.0000
Vietnam,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Yemen,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [34]:

#connect to database 
engine = create_engine("mysql://root:J****2028@localhost/oilprod_db")

# load the dataframe into oilprod_db sql data base 

df_data.to_sql('oil_prod_price',engine, if_exists = 'append', index=False)